// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetImagesNameOKCode is the HTTP code returned for type GetImagesNameOK
const GetImagesNameOKCode int = 200

/*
GetImagesNameOK Returns the Gopher

swagger:response getImagesNameOK
*/
type GetImagesNameOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetImagesNameOK creates GetImagesNameOK with default headers values
func NewGetImagesNameOK() *GetImagesNameOK {

	return &GetImagesNameOK{}
}

// WithPayload adds the payload to the get images name o k response
func (o *GetImagesNameOK) WithPayload(payload io.ReadCloser) *GetImagesNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get images name o k response
func (o *GetImagesNameOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImagesNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
