// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAPIAPIVersionHandlerFunc turns a function with the right signature into a get API API version handler
type GetAPIAPIVersionHandlerFunc func(GetAPIAPIVersionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPIAPIVersionHandlerFunc) Handle(params GetAPIAPIVersionParams) middleware.Responder {
	return fn(params)
}

// GetAPIAPIVersionHandler interface for that can handle valid get API API version params
type GetAPIAPIVersionHandler interface {
	Handle(GetAPIAPIVersionParams) middleware.Responder
}

// NewGetAPIAPIVersion creates a new http.Handler for the get API API version operation
func NewGetAPIAPIVersion(ctx *middleware.Context, handler GetAPIAPIVersionHandler) *GetAPIAPIVersion {
	return &GetAPIAPIVersion{Context: ctx, Handler: handler}
}

/*
	GetAPIAPIVersion swagger:route GET /api/{api_version} getApiApiVersion

Returns a api version
*/
type GetAPIAPIVersion struct {
	Context *middleware.Context
	Handler GetAPIAPIVersionHandler
}

func (o *GetAPIAPIVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPIAPIVersionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
