// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIAPIVersionParams creates a new GetAPIAPIVersionParams object
//
// There are no default values defined in the spec.
func NewGetAPIAPIVersionParams() GetAPIAPIVersionParams {

	return GetAPIAPIVersionParams{}
}

// GetAPIAPIVersionParams contains all the bound params for the get API API version operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAPIAPIVersion
type GetAPIAPIVersionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*this is the api version number.
	  Required: true
	  In: path
	*/
	APIVersion int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAPIAPIVersionParams() beforehand.
func (o *GetAPIAPIVersionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAPIVersion, rhkAPIVersion, _ := route.Params.GetOK("api_version")
	if err := o.bindAPIVersion(rAPIVersion, rhkAPIVersion, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAPIVersion binds and validates parameter APIVersion from path.
func (o *GetAPIAPIVersionParams) bindAPIVersion(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("api_version", "path", "int64", raw)
	}
	o.APIVersion = value

	return nil
}
