// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUsersUserOKCode is the HTTP code returned for type GetUsersUserOK
const GetUsersUserOKCode int = 200

/*
GetUsersUserOK Returns the greeting to the user

swagger:response getUsersUserOK
*/
type GetUsersUserOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetUsersUserOK creates GetUsersUserOK with default headers values
func NewGetUsersUserOK() *GetUsersUserOK {

	return &GetUsersUserOK{}
}

// WithPayload adds the payload to the get users user o k response
func (o *GetUsersUserOK) WithPayload(payload string) *GetUsersUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users user o k response
func (o *GetUsersUserOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetUsersUserBadRequestCode is the HTTP code returned for type GetUsersUserBadRequest
const GetUsersUserBadRequestCode int = 400

/*
GetUsersUserBadRequest Invalid character in "user" were provided

swagger:response getUsersUserBadRequest
*/
type GetUsersUserBadRequest struct {
}

// NewGetUsersUserBadRequest creates GetUsersUserBadRequest with default headers values
func NewGetUsersUserBadRequest() *GetUsersUserBadRequest {

	return &GetUsersUserBadRequest{}
}

// WriteResponse to the client
func (o *GetUsersUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
