// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Rest API server in Go with Swagger endpoints definition.",
    "title": "go-rest-api",
    "version": "0.1.0"
  },
  "paths": {
    "/": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message.",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/api/{api_version}": {
      "get": {
        "description": "Returns a api version",
        "parameters": [
          {
            "type": "integer",
            "description": "this is the api version number.",
            "name": "api_version",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "returns the api version",
            "schema": {
              "type": "integer"
            }
          },
          "400": {
            "description": "Invaid character as api version provided"
          }
        }
      }
    },
    "/images/{name}": {
      "get": {
        "description": "Returns the Gopher image",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "The name of the gopher to display",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the Gopher",
            "schema": {
              "type": "file"
            }
          }
        }
      }
    },
    "/users/{user}": {
      "get": {
        "description": "Returns greeting to the user",
        "parameters": [
          {
            "type": "string",
            "description": "The name of the user to greet",
            "name": "user",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the greeting to the user",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid character in \"user\" were provided"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Rest API server in Go with Swagger endpoints definition.",
    "title": "go-rest-api",
    "version": "0.1.0"
  },
  "paths": {
    "/": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK message.",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/api/{api_version}": {
      "get": {
        "description": "Returns a api version",
        "parameters": [
          {
            "type": "integer",
            "description": "this is the api version number.",
            "name": "api_version",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "returns the api version",
            "schema": {
              "type": "integer"
            }
          },
          "400": {
            "description": "Invaid character as api version provided"
          }
        }
      }
    },
    "/images/{name}": {
      "get": {
        "description": "Returns the Gopher image",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "The name of the gopher to display",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the Gopher",
            "schema": {
              "type": "file"
            }
          }
        }
      }
    },
    "/users/{user}": {
      "get": {
        "description": "Returns greeting to the user",
        "parameters": [
          {
            "type": "string",
            "description": "The name of the user to greet",
            "name": "user",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the greeting to the user",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid character in \"user\" were provided"
          }
        }
      }
    }
  }
}`))
}
